# Site settings
title: Julien Teruel
description: Online Cv Julien Teruel
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Julien Téruel
user_description: Je suis actuellement Lead Developer chez Worldline.</br>Dans une équipe de 10 personnes en fonctionnement agile (Scrum), j'assure le rôle de Lead Developper sur le portefeuille électronique Paylib.</br>Mes tâches de tous les jours sont :<ul><li>Support technique auprès des autres développeurs</li><li>Décideur technique sur les solutions de la plateforme avec la direction technique générale</li><li>Validation de la qualité des commits des developpeurs au travers de l'outils Gitlab et des merge request</li><li>Prise de ticket du Sprint pour analyse de bugs/développement</li><li>Traitement des incidents de productions</li></ul>
user_title: Lead Software Developer
email: julien.teruel@gmail.com
twitter_username: lorem_ipsum
github_username:  jt117
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-97338162-1"

exclude: ['package.json', 'src' , 'node_modules']
